FROM python:3

WORKDIR /usr/src/py-server

RUN git clone https://github.com/tgmichail/diploma_thesis.git .

RUN pip install -r ./requirements.txt

# this solves ImportError: libGL.so.1: cannot open shared object file: No such file or directory
#should it be on the dependencies?
RUN apt-get update && apt-get install -y libgl1

VOLUME /usr/src/py-server

CMD ["python3", "server.py"]
